# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  database: ferret_development
  username: ferret
  password: ferret
  socket: /var/run/mysqld/mysqld.sock
  
test:
  adapter: mysql
  database: ferret_test
  username: ferret
  password: ferret
  socket: /var/run/mysqld/mysqld.sock

# since this is a demo, we won't need this one
production:
  adapter: mysql
  database: ferret_production
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

