production:
  host: ferret.yourdomain.com
  port: 9010
  pid_file: log/ferret.pid
development:
  host: localhost
  port: 9010
  pid_file: log/ferret.pid
test:
  host: localhost
  port: 9009
  pid_file: log/ferret.pid
  log_file: log/ferret_server_test.log
  log_level: info

